name: Quality Gate Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  quality-gate:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: The Lint Gate
        run: npm run lint

      - name: The Unit Test Gate
        run: npm run test

      - name: Build Gate
        run: npm run build
